Added files related to slider component
CameronHildebrandt/NeurAlbertaTech pull request #37
Opened 2021-11-12 05:40 UTC by judzelicor

- Slider Color scheme works for dark and light mode.
- Mobile responsive but if you don't feel satisfied please tell on how I should improve it.
- If I'm breaking any clean code conventions and whatnot (especially on my css) please do tell me.
- I'll clean up the code for the slider right after your feedback.
- Any input welcome!!!

2021-11-12 05:44 UTC, judzelicor commented
Huh, I just visited the preview and somehow the controls for the slider are positioned way at the top however in my environment it's inside the slider.

2021-11-12 05:45 UTC, judzelicor commented
Oh wait I found my mistake  that's causing this.

2021-11-21 21:19 UTC, zacharyselk requested changes

2021-11-21 21:19 UTC, zacharyselk commented on public/test.html
> +</html>
Remove this file.

2021-11-21 21:19 UTC, zacharyselk commented on public/components/carousel/slider.js
> +  console.log(HTMLSlider)
Remove unneeded logging

2021-11-21 21:19 UTC, zacharyselk commented on public/components/carousel/slider.css
> +}
Currently this flex-box stretches across the sliderContainer and covers anything that appears behind it. This is causes most of the button  in the cards to be covered and not receive to `hover` or `click` events.

2022-03-17 03:50 UTC, closed without merging